const
  SVG_ANCHOR_LEFT = 0,
  SVG_ANCHOR_CENTER = 1,
  SVG_ANCHOR_RIGHT = 2,
  SVG_ANCHOR_TOP = 0,
  SVG_ANCHOR_MIDDLE = 1,
  SVG_ANCHOR_BOTTOM = 2


export {SVG_ANCHOR_LEFT,SVG_ANCHOR_CENTER,SVG_ANCHOR_RIGHT,SVG_ANCHOR_TOP,SVG_ANCHOR_MIDDLE,SVG_ANCHOR_BOTTOM}