name: Build/release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Remove piper Darwin
        run: rm -r extraResources/piper/darwin
        if: ${{ ! startsWith(matrix.os, 'macos') }}

      - name: Remove piper linux
        run: rm -r extraResources/piper/linux
        if: ${{ ! startsWith(matrix.os, 'ubuntu') }}

      - name: Remove piper win32
        run: rm -r extraResources/piper/win32
        if: ${{ ! startsWith(matrix.os, 'windows') }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
